#!/bin/sh /etc/rc.common

USE_PROCD=1
START=80
STOP=10

ROUTERPILOT_BIN="/usr/bin/routerpilot"
UCI_PACKAGE="routerpilot"

start_service() {
	local port host log_level read_only dry_run

	config_load "$UCI_PACKAGE"
	config_get port settings port "8080"
	config_get host settings host "0.0.0.0"
	config_get log_level settings log_level "info"
	config_get_bool read_only settings read_only 1
	config_get_bool dry_run settings dry_run 0

	procd_open_instance
	procd_set_param command "$ROUTERPILOT_BIN" serve
	procd_set_param env ROUTERPILOT_PORT="$port"
	procd_set_param env ROUTERPILOT_HOST="$host"
	procd_set_param env ROUTERPILOT_LOG_LEVEL="$log_level"

	[ "$read_only" = "1" ] && procd_set_param env ROUTERPILOT_READ_ONLY="true"
	[ "$dry_run" = "1" ] && procd_set_param env ROUTERPILOT_DRY_RUN="true"

	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "routerpilot"
}

reload_service() {
	stop
	start
}
